# Generated by Django 5.2.3 on 2025-07-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('is_published', models.BooleanField(default=True)),
                ('poster', models.ImageField(blank=True, upload_to='posters/%Y/%m/')),
                ('genre', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
